spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeffrey?serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.shortenurl.model
  global-config:
    db-config:
      id-type: UUID